---
# tasks file for apache2
- name: Install the latest version of Apache and python3
  ansible.builtin.package:
    name:
      - apache2
      - python-apt
      - php
      - libapache2-mod-php
      - php-mysql
    state: latest
  become: yes
  notify: restart apache2 servers

- name: Copy Apache configuration file
  ansible.builtin.copy:
    src: 'apache2.conf'
    dest: /etc/apache2/apache.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2 servers

  - name: Copy index.html file
  ansible.builtin.copy:
    src: 'index.html'
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2 servers

- name: Copy index.php file
  ansible.builtin.copy:
    src: 'index.php'
    dest: /var/www/html/index.php
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2 servers

- name: Create symbolic link
  ansible.builtin.file:
    src: /etc/apache2/mods-available/headers.load
    dest: /etc/apache2/mods-enabled/headers.load
    state: link
  notify: restart apache2 servers

